name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install gatsby
      run: |
        npm install -g gatsby-cli
        gatsby new gatsby-blog https://github.com/gatsbyjs/gatsby-starter-blog
        rm -rf gatsby-blog/content/blog/
        mv blog gatsby-blog/content/
        cd gatsby-blog
        gatsby build
        cd ..
        echo $(pwd)
        cd gatsby-blog/public
        git init
        git config --global user.name "hebinhao1993"
        git config --global user.email "hebinhao1993@outlook.com"
        git add --all .
        git commit -m "Action Auto Builder"
        git push --quiet --force https://$ACCESS_TOKEN@github.com/hebinhao1993/test.git gh-pages
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
